### PR TITLE
Changes for 1.0.5

### PR DESCRIPTION
**Pull request by enigmaquip**

### CODE REVIEW

**Comment by enigmaquip** [comment]
Closes #131 not 141

**Comment by enigmaquip** [comment]
Closes #126

**Comment by enigmaquip** [comment]
Last piece to close #85

**Comment by LunarLunarLunar** [comment]
add recipe to obtain soul lava bee without requiring soul lava.

**Comment by enigmaquip** [comment]
> add recipe to obtain soul lava bee without requiring soul lava.

A) This is not the right place to post that comment and B) At this time we will not be making that an option

**Pull request merged**
